# .github/workflows/run-tests.yml
name: Java Tests direkt mit src/test/test.sh

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Java installieren
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Testskript ausführen
        run: |
          chmod +x src/test/test.sh
          src/test/test.sh
